nanoleaf_token = "my_access_token"
# If you need to manually specify the nanoleaf connection details you can do so here.
# Omitting this will instead discover the device via mDNS.
# nanoleaf_host = "nanoleaf_ip"
# nanoleaf_port = 16021