on: [push, pull_request]
name: Test
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt update && sudo apt install llvm-config
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
            components: clippy
            default: true
            toolchain: stable
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test